import {
  LayoutDashboard,
  Briefcase,
  Users,
  FileText,
  Settings,
  Building,
  FlaskConical,
  ClipboardCheck,
  User,
  Bell,
  Shield,
  MessageSquare,
  BarChart,
  BookOpen,
  HelpCircle,
} from 'lucide-react';

export const NAV_LINKS = {
  EMPLOYER: [
    { href: '/employer/dashboard', label: 'Dashboard', icon: LayoutDashboard },
    { href: '/messages', label: 'Chat', icon: MessageSquare },
    { href: '/employer/jobs', label: 'Manage Jobs', icon: Briefcase },
    { href: '/employer/profile', label: 'Profile Settings', icon: Building },
    { href: '/settings', label: 'Settings', icon: Settings },
    { href: '/in-lab', label: 'In-Lab Mode', icon: FlaskConical },
  ],
  SCIENTIST: [
    { href: '/scientist/dashboard', label: 'Dashboard', icon: LayoutDashboard },
    { href: '/messages', label: 'Chat', icon: MessageSquare },
    { href: '/jobs', label: 'Browse Jobs', icon: Briefcase },
    { href: '/scientist/profile', label: 'My Profile', icon: User },
    { href: '/settings', label: 'Settings', icon: Settings },
    { href: '/in-lab', label: 'In-Lab Mode', icon: FlaskConical },
  ],
  COLLABORATOR: [
    { href: '/collaborator/dashboard', label: 'Dashboard', icon: LayoutDashboard },
    { href: '/messages', label: 'Chat', icon: MessageSquare },
    { href: '/collaborator/projects', label: 'Projects', icon: FlaskConical },
    { href: '/collaborator/tasks', label: 'My Tasks', icon: ClipboardCheck },
    { href: '/collaborator/profile', label: 'My Profile', icon: User },
    { href: '/settings', label: 'Settings', icon: Settings },
  ],
  ADMIN: [
    { href: '/admin/dashboard', label: 'Dashboard', icon: LayoutDashboard },
    { href: '/admin/users', label: 'Manage Users', icon: Users },
    { href: '/admin/jobs', label: 'Manage Jobs', icon: Briefcase },
    { href: '/messages', label: 'Chat', icon: MessageSquare },
    { href: '/admin/analytics', label: 'Analytics', icon: BarChart },
    { href: '/admin/system-logs', label: 'System Logs', icon: FileText },
    { href: '/admin/payroll', label: 'Payroll', icon: Shield },
    { href: '/admin/blog', label: 'Blog', icon: BookOpen },
    { href: '/admin/faq', label: 'Manage FAQs', icon: HelpCircle },
    { href: '/admin/notifications', label: 'Notifications', icon: Bell },
  ],
};
