import {
  LayoutDashboard,
  Briefcase,
  Users,
  FileText,
  Settings,
  Building,
  FlaskConical,
  ClipboardCheck,
  User,
  Bell,
  Shield,
  MessageSquare,
  BarChart,
} from 'lucide-react';

export const NAV_LINKS = {
  EMPLOYER: [
    { href: '/employer/dashboard', label: 'Dashboard', icon: LayoutDashboard },
    { href: '/messages', label: 'Chat', icon: MessageSquare },
    { href: '/employer/jobs', label: 'Manage Jobs', icon: Briefcase },
    { href: '/employer/profile', label: 'Company Profile', icon: Building },
    { href: '/employer/settings', label: 'Settings', icon: Settings },
  ],
  SCIENTIST: [
    { href: '/scientist/dashboard', label: 'Dashboard', icon: LayoutDashboard },
    { href: '/messages', label: 'Chat', icon: MessageSquare },
    { href: '/jobs', label: 'Browse Jobs', icon: Briefcase },
    { href: '/scientist/profile', label: 'My Profile', icon: User },
    { href: '/scientist/settings', label: 'Settings', icon: Settings },
  ],
  COLLABORATOR: [
    { href: '/collaborator/dashboard', label: 'Dashboard', icon: LayoutDashboard },
    { href: '/messages', label: 'Chat', icon: MessageSquare },
    { href: '/collaborator/projects', label: 'Projects', icon: FlaskConical },
    { href: '/collaborator/tasks', label: 'My Tasks', icon: ClipboardCheck },
    { href: '/collaborator/profile', label: 'My Profile', icon: User },
    { href: '/collaborator/settings', label: 'Settings', icon: Settings },
  ],
  ADMIN: [
    { href: '/admin', label: 'Dashboard', icon: LayoutDashboard },
    { href: '/admin/users', label: 'Manage Users', icon: Users },
    { href: '/admin/jobs', label: 'Manage Jobs', icon: Briefcase },
    { href: '/messages', label: 'Chat', icon: MessageSquare },
    { href: '/admin/analytics', label: 'Analytics', icon: BarChart },
    { href: '/admin/system-logs', label: 'System Logs', icon: FileText },
    { href: '/admin/payroll', label: 'Payroll', icon: Shield },
    { href: '/admin/notifications', label: 'Notifications', icon: Bell },
  ],
};
